### ISSUE TITLE
Rake should be a dependency

### ISSUE THREAD

**Issue by andrewmcodes** [dvmonroe/release-notes#85]
# Issue

Rake is a dependency of the gem, and trying to run commands like `bin/release-notes generate --ignore-head` will fail with the stack trace below if rake is not installed in the project.

## Environment

- Ruby **2.6.4**
- release-notes **4.1.0**

## Current behavior

```
Traceback (most recent call last):                                                                                   
        7: from bin/release-notes:29:in `<main>'                                                                     
        6: from bin/release-notes:29:in `load'                                                                       
        5: from /Users/andrew.mason/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/release-notes-4.1.0/exe/release-no
tes:6:in `<top (required)>'                                                                                          
        4: from /Users/andrew.mason/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/release-notes-4.1.0/exe/release-no
tes:6:in `require'                                                                                                   
        3: from /Users/andrew.mason/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/release-notes-4.1.0/lib/release/no
tes.rb:26:in `<top (required)>'                                                                                      
        2: from /Users/andrew.mason/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/release-notes-4.1.0/lib/release/no
tes.rb:26:in `require'                                                                                               
        1: from /Users/andrew.mason/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/release-notes-4.1.0/lib/release/no
tes/install.rb:3:in `<top (required)>'                                                                               
/Users/andrew.mason/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/release-notes-4.1.0/lib/release/notes/install.rb:3
:in `require': cannot load such file -- rake (LoadError)   
```

## Expected behavior

Rake will be included as a dependency of the gem so this error does not occur.

**Comment by dvmonroe** [comment]
Absolutely right. Good to hear from you @andrewmcodes. Thanks for reporting.
